### ISSUE TITLE
Doesn't work under FreeBSD 13.1

### ISSUE THREAD

**Issue by iron-udjin** [bjesus/clapboard#1]
$ env RUST_BACKTRACE=full clapboard 
```
thread 'main' panicked at 'Failed to start command: Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/main.rs:104:10
stack backtrace:
   0:        0xe2717ef4f - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h919bef3d5abebde9
   1:        0xe271973be - core::fmt::write::h6413343c5226105f
   2:        0xe2715d945 - std::io::Write::write_fmt::had0ddcb25461208f
   3:        0xe2717ed05 - std::sys_common::backtrace::print::h5ed9962f90e9b258
   4:        0xe2716bd0f - std::panicking::default_hook::{{closure}}::h3978a8a8f5c1f893
   5:        0xe2716b9a1 - std::panicking::default_hook::h0cdbdd5201407347
   6:        0xe2716c3cb - std::panicking::rust_panic_with_hook::h15bc8b6da20c2af3
   7:        0xe2717f2a7 - std::panicking::begin_panic_handler::{{closure}}::h082a693f9436206b
   8:        0xe2717f09c - std::sys_common::backtrace::__rust_end_short_backtrace::h56343aa2331ff455
   9:        0xe2716bf52 - rust_begin_unwind
  10:        0xe27196663 - core::panicking::panic_fmt::hf18d1d226927e137
  11:        0xe2719bbb3 - core::result::unwrap_failed::ha5725a0b4539229c
  12:        0xe27144816 - clapboard::main::hb1a1464cfff07260
  13:        0xe27145933 - std::sys_common::backtrace::__rust_begin_short_backtrace::hde3d401afab08dba
  14:        0xe27137229 - std::rt::lang_start::{{closure}}::hc50cfc3e00971e09
  15:        0xe271623a4 - std::rt::lang_start_internal::hadf3843363799440
  16:        0xe27144fb5 - main
```

**Comment by bjesus** [comment]
Hey! Thanks for reporting. just to confirm, do you have `tofi` installed, and is it in your $PATH?

**Comment by iron-udjin** [comment]
I have wofi installed and it's in my $PATH.

**Comment by bjesus** [comment]
Clapboard defaults to using `tofi`. If you want to use `wofi`, you need to create a configuration file and specify the `launcher` parameter, like the README mentions. Did you do this?

**Comment by iron-udjin** [comment]
There is no mention that I _should_ change default config in case I use anything other except **tofi**. I thought that the program in case it cannot find **tofi** will look for other menu-like program from the list above. It would be great to fix this missunderstanding in documentation. 

What is the correct way to run with wofi? In _~/.config/clapboard/config.toml_ I have:
`launcher = [ "wofi", "--dmenu" ]`
When I launch _clapboard_ I see list of clipboard entries and when I click on it nothing happen. As far as I understood, it should paste word/line to STDOUT. Is it correct?

**Comment by bjesus** [comment]
it doesn't automatically paste, it just moves the entry to the clipboard. you should then paste using `Ctrl+V` or however you're normally pasting. It's a nice idea to automatically paste, I'll consider that!

**Comment by iron-udjin** [comment]
Ok, got it. Let's close this issue.
