### ISSUE TITLE
Can you make a release?

### ISSUE THREAD

**Issue by lz-coder** [bjesus/clapboard#2]

**Comment by bjesus** [comment]
I can do it for sure, but can I ask why do you need it?

**Comment by lz-coder** [comment]
> I can do it for sure, but can I ask why do you need it?

I wanted to package it for Void Linux, but they only accept packages in the repositories that have been released.

**Comment by bjesus** [comment]
done: https://github.com/bjesus/clapboard/releases/tag/v0.1.1

thank you for packaging it!

**Comment by lz-coder** [comment]
> done: https://github.com/bjesus/clapboard/releases/tag/v0.1.1
> 
> thank you for packaging it!

Thank you for the release!
