### ISSUE TITLE
feat: remove tofi from AUR package

### ISSUE THREAD

**Issue by Yushi5058** [bjesus/clapboard#3]
Hello,
I would like to address an issue for me since I like the concept of your clipboard manager. Is it possible to remove the required dependency (tofi) from the AUR package ?  For someone who uses sway-wm with rofi wayland fork, I think that an agnostic menu launcher for clapboard would be awesome.
Thanks,
Yushi

**Comment by bjesus** [comment]
Thanks for the suggestion, I've just updated the AUR package to mark tofi as an optional dependency.
