### ISSUE TITLE
feat: add vim-like keymaps and other ideas

### ISSUE THREAD

**Issue by Yushi5058** [bjesus/clapboard#4]
Hello again,
I have a suggestion to add. Add vim-like keymaps to be able to delete clipboards contents.
For example : 
* hjkl for navigation between clipboards contents instead of fuzzy find ( h for left, l for right, k for up and j for down)
* /{cmd} to fuzzy-find through the clipboards contents, accept regex expressions too 
* d will delete the line (without copying it like in vim) of the clipboard content the cursor is in 
*  keymap to delete the whole clipboard history with a confirm popup like
*  y will copy the clipboard content the cursor is in to use it outside the clipboard manager
*  clipboard contents are read-only to avoid conflicts 
*  ability to configure a color-background to determine the actual line we are in ( where the cursor is in )

you can get some inspiration from a neovim / vim plugin where we can adopt some similarities for a completely fully functionnal clipboard manager, here's the [link](https://github.com/stevearc/oil.nvim)

Hope it helps,
Thanks,
Yushi

**Comment by bjesus** [comment]
Thanks for the issue. Since clapboard doesn't have it's own interface, but instead instead it use's the launcher of your choice, I do not see how this can ever be implemented (unless we create a Clapboard-specific launcher, which seems like an overkill).

**Comment by Yushi5058** [comment]
Hello, maybe the commands used to store clapboard contents can be used to wipe clapboard etc

**Comment by bjesus** [comment]
Closing this issue as it seems out of scope of Clapboard.
