### ISSUE TITLE
thread 'main' panicked at src/main.rs:130:10:

### ISSUE THREAD

**Issue by falcon71181** [bjesus/clapboard#6]
thread 'main' panicked at src/main.rs:130:10:
Failed to start command: Os { code: 2, kind: NotFound, message: "No such file or directory" }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by bjesus** [comment]
you need to install `tofi` or specify another launcher in the config

**Comment by falcon71181** [comment]
> you need to install `tofi` or specify another launcher in the config

i have wofi

**Comment by bjesus** [comment]
so see the Configuration section in the README and configure it to use to `wofi` :)
